# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - 3.6
  - 3.5
  - 3.4

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - env
  - rm miniconda.sh
  - source $HOME/miniconda/bin/activate base
  - conda install -c conda-forge pre-commit
  - Rscript -e "install.packages('remotes')"
  - Rscript -e "remotes::install_github('lorenzwalthert/precommit')"
  - sed -i -n '/lintr/!p' .pre-commit-config.yaml
  - if [[ ${TRAVIS_R_VERSION_STRING} == 3.6 ]]; then pre-commit install && pre-commit run --all; fi
